### PR TITLE
Wkb converter and entity framework converter

### PR DESCRIPTION
**Pull request by alvaromongon**
Hi guys, 

I would like to add two new converters to the repository.

I have updated references to latest GeoJson library and SQL DataTypes.

Take a look please.

### CODE REVIEW

**Comment by xfischer** [comment]
Hi @alvaromongon !
Thanks for your contribution. I've merged your changes and I had problem with SqlSpatial dlls not included.
I have fixed it by reinstalling NuGet packages and it's OK now.
A test fails (about incorrect windings), because it does not throw an exception has excpected.

**Comment by alvaromongon** [comment]
Hi @xfischer,

Thank you for the great job with the GeoJson library.

I think I know what test you are talking about, it should be throwing the exception, and least it was throwing it in my environment and it made sense since the geographycal restrictions were not met.

I was more worry about the tests I had to skip because the equal was not working.

In any case, I would like to ask you about the nuget package creation, Is there any automation in place to generate the nuget package or I should do it my self?

**Comment by xfischer** [comment]
Hi @alvaromongon, sorry for the late answer.
I have to create and deploy the package myself.
I think I'll create separate package and libraries for Entity, MSSQL, etc.
I'll see what I can do in the next days

**Comment by alvaromongon** [comment]
That makes total sense @xfischer , That is why I created a different nuspec for each of the features.

**Comment by xfischer** [comment]
Done ! Closes #14

**Comment by alvaromongon** [comment]
Great, thanks!

**Pull request merged**
