### PR TITLE
Indicate that 3D geometries are not supported.

### PR DESCRIPTION
**Pull request by stijnherreman**

### CODE REVIEW

**Comment by stijnherreman** [comment]
Hi @xfischer, it should be possible to fix this yes, `IPosition` supports it at least. I might submit a PR, haven't decided yet. I considered migrating this part of our code to NTS but that also has a few blockers for our scenario, so I need to evaluate which path to continue on.

**Comment by xfischer** [comment]
And WKB supports it too : https://en.wikipedia.org/wiki/Well-known_text_representation_of_geometry

@alvaromongon you were the original contributor of Wkb for GeoJson.net. Any chance you can add support of Z coordinates ?

@stijnherreman OK, feel free to submit an PR if you made things work in this repo.
If you're stuck I may try to help if I'm not too busy with my other projects.

**Comment by stijnherreman** [comment]
Indeed, it's a matter of adding support for types 1001-1007. The mentioned exception is intentionally thrown here: https://github.com/GeoJSON-Net/GeoJSON.Net.Contrib/blob/5d13b5b642bcaadaec896f5de26205ec1e50dd52/src/GeoJSON.Net.Contrib.Wkb/Conversions/WkbDecode.cs#L159

**Comment by xfischer** [comment]
I don't think it should be too hard. I wish I had more time to do this, but not at the moment.

**Pull request merged**
