### PR TITLE
Fixed conversions for empty "Multi" types and GeometyCollection with nested "Multi" types

### PR DESCRIPTION
**Pull request by xfischer**

### CODE REVIEW

**Comment by xfischer** [comment]
Here we go for .net45 and Json 8.0.2

**Comment by jbattermann** [comment]
Alright perfect! I'll update the nuspec real quick and build/push the updated package right away.. just a sec..

**Comment by jbattermann** [comment]
Thanks Xavier - fyi, I've made you a 'Collaborator' for the repo so you can pull in PRs etc, too if you want to.

Builds are automatically triggered on Appeyor - pushes to NuGet.org are currently manual only to reduce the frequency of new versions.

**Comment by xfischer** [comment]
I'm proud of this, thank you Jörg !

**Pull request merged**
