### PR TITLE
Enable NuGet symbol package generation

### PR DESCRIPTION
**Pull request by milang**
This pull request enables NuGet symbol package (`.snupkg`) generation for all three GeoJSON.Net contribution projects. Symbol packages enable _"Go to definition"_ as well as _"(Debugger) Step into method"_ IDE features. From [Microsoft documentation for `.snupkg`](https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg):

> A good debugging experience relies on the presence of debug symbols as they provide critical information like the association between the compiled and the source code, names of local variables, stack traces, and more. You can use symbol packages (.snupkg) to distribute these symbols and improve the debugging experience of your NuGet packages.

Additional changes:
- Extends _Contribution Guide_ with steps to create NuGet packages and push them to NuGet server from command line
- Adds [SourceLink](https://github.com/dotnet/sourcelink) with deterministic symbol generation for `Release` builds. [Microsoft guidance for SourceLink](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/sourcelink) recommends: _"CONSIDER enabling deterministic builds. Deterministic builds enable verification that the resulting binary was built from the specified source and provide traceability."_
- Bumps all dependencies to the latest version
    - `EntityFramework`, `6.1.3` => `6.4.4`
    - `Microsoft.SqlServer.Types`, `14.0.314.76` => `14.0.1016.290`: I wasn't sure if `GeoJSON.Net.Contrib` stayed on previous 14 version on purpose, but all our ([Pandell](https://github.com/pandell/)) projects have been using the latest 14 version without issues across all SQL Server versions we support.
    - Originally this PR also updated `GeoJSON.Net` from `1.2.15` to `1.2.19`, but @xfischer already did that when merging my previous commit #31, thank you.
- Adds XML documentation file generation (e.g. `GeoJSON.Net.Contrib.MsSqlSpatial.xml`). This allows IDE to display additional information about classes and methods during development.
- Adds icon to all `.nuget` packages. I used [GeoJson twitter](https://twitter.com/GeoJSON) avatar. We should get their permission to use the avatar image as package icon, but I don't have a Twitter account so couldn't DM them.
- Removes automatic `.nuget` generation during build (`GeneratePackageOnBuild` property). IMO `.nuget` packages should be generated by a separate command on a clean repository (i.e. preceded by `git clear` as documented in `README.md`), not during development process. I also recommend packaging the `Release` build, not the default `Debug` build that is used during development.
- Moves properties that have the same value across all contribution projects to `src/Directory.Build.props`. This keeps only the properties that are project-specific in project's `.csproj` file.

For comparison, this is the latest `GeoJSON.Net.Contrib.MsSqlSpatial` package published today:

Latest published GeoJSON.Net.Contrib.MsSqlSpatial

And package generated with this PR's changes:

GeoJSON.Net.Contrib.MsSqlSpatial with this PR's changes

### CODE REVIEW

**Comment by xfischer** [comment]
Hi @milang.
Thanks for this clear and factual PR. That's a great work! I've learned a lot from this PR ! Wow. SourceLink is amazing.
Asked permission for picture use : https://twitter.com/XavierFischer/status/1278731075099987968

I'm reviewing the details and let you know. Can't wait to test it.

**Comment by xfischer** [comment]
Hi @milang. I'm going to try generating NuGets with the tooling doc you left in the readme ;)

**Comment by xfischer** [comment]
@milang dotnet test runs only well for MSTest project (MsSqlSpatial). Other projects using xUnit tests are not run.
dotnet test says that no adapter could be found, but everything seems OK.
Did you run into this issue ?

**Comment by xfischer** [comment]
Found a fix: seems that the 
```
<TargetFrameworks>$(DefaultTargetFramework)</TargetFrameworks>
```
token does not plays well with xUnit projects.
If I set it to net461 it is OK.

**Comment by milang** [comment]
Good find @xfischer , sorry about that. You might have noticed in my screenshot that I only tested using `net48`. I don't have `net45` targeting pack installed on my development computer (on purpose).

I think the problem is caused by `xunit` only being available for `net452` (and `netcoreapp2.1`). `GeoJSON.Net.Contrib` test build should therefore work for anything `net452`-and-newer (including `net461` that you used). For example, `xunit.runner.visualstudio` package looks like this:
xunit build runner

You might consider compiling `src/*` projects for `net45` as before, and compiling `test/*` projects for `net48`. Most if not all developers will be running the tests using .NET 4.8 runtime regardless of compilation target, because Windows Update has had .NET 4.8 as an important update for a long time now.

**Pull request merged**
