### PR TITLE
MsSqlSpatial commit from PR 31

### PR DESCRIPTION
**Pull request by xfischer**

### CODE REVIEW

**Comment by xfischer** [comment]
Build failed because of missing GeoJson.Net reference (added it through NuGet). Will double check.

**Comment by jbattermann** [comment]
Great, thanks @xfischer !

**Comment by jbattermann** [comment]
I've opened an issue #2 to track / create a nuspec / nuget package so it'll get properly published, too.. I'll try to get it setup over the weekend

**Comment by xfischer** [comment]
Glad to help !

**Comment by jbattermann** [comment]
just a quick update: It's up on nuget.org now - http://www.nuget.org/packages/GeoJSON.Net.Contrib.MsSqlSpatial/

**Comment by xfischer** [comment]
Cool ! I'll add XML comments and a decent readme. Thanks Jörg.

**Comment by xfischer** [comment]
I'm really proud of seeing my name on NuGet ! Thanks Jörg for putting this live.
Xavier

Date: Thu, 5 Nov 2015 11:10:00 -0800

**Pull request merged**
