### PR TITLE
Add SQL server types reference

### PR DESCRIPTION
**Pull request by Neorth**
Fixes EntityFramework tests.

### CODE REVIEW

**Comment by xfischer** [comment]
Not sure about this. This will oblige callers to migrate to SqlTypes 14, I think this would cause runtime errors when playing around with older types (ie SQL 2008 R2)

**Comment by Neorth** [comment]
You're probably right in that. Do you have any other walk-around to make tests running in newer environments?

**Comment by xfischer** [comment]
What's the exact problem ? The tests don't run in your environment ?
I'll try to launch them later on today.

SQL Types have been a headache since the beginning. A good workaround was to use Serialize/Deserialze from binary as long as I remember. More on that later.

**Comment by Neorth** [comment]
Just tested on a freshly installed computer but gets the same result:
image
There might be other solutions to this than mine but I feel it should at least work out of the box without having to install something systemwide.

**Comment by xfischer** [comment]
Hi @Neorth What would you need EF for ? I think the next step if you're into EF should be to install SQL Server isn't it ? Aaannnd this may fix the problem. Let me know.

@alvaromongon, hi! Any ideas on that, as you were the main contributor for this side of GeoJSON.Net

**Comment by Neorth** [comment]
Not necessarily, I'm using an Azure SQL DB that keeps track of user posted geometries as DbGeometries.

**Comment by xfischer** [comment]
OK @Neorth. Let's give @alvaromongon two days.
Passed this delay, I'll merge your PR.

Thanks!

**Comment by milang** [comment]
@xfischer please note that this PR has been obsoleted by #31 (which is now merged into `master`). I recommend closing this pull request.

@Neorth could you please try re-running the tests using the latest `master`? As long as you have .NET Core SDK 3.0+ (which you should have if you installed Visual Studio 2019), the tests should now "just work" both on the command line (see [README.md](https://github.com/GeoJSON-Net/GeoJSON.Net.Contrib#build-test-and-package-the-solution))  and in your IDE.

**Comment by xfischer** [comment]
Closing this PR, please feel free to add any comments here.

**Pull request closed without merging**
